name: adl-proj
channels:
  - conda-forge
  - anaconda
dependencies:
  - pip
  - python=3.7
  - numpy
  - panda
  - scikit-learn
  - prefect
  - beautifulsoup4
  - flask
  - flask-sqlalchemy
  - psycopg2
  - pip:
      - basilica
