name: adl-proj
channels:
  - conda-forge
  - anaconda
dependencies:
  - pip
  - python=3.7
  - numpy
  - pandas
  - scikit-learn
  - prefect
  - beautifulsoup4
  - sqlalchemy
  - python-dotenv
  - pip:
      - basilica
